crds:
  enabled: true

featureGates: "ExperimentalGatewayAPISupport=true"

# workload identity annotation is injected by the deploy script via --set
serviceAccount:
  annotations: {}

podLabels:
  azure.workload.identity/use: "true"

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule

cainjector:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule

webhook:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule

startupapicheck:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule