apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
  namespace: default
type: Opaque
stringData:
  azure.json: |
    {
      "subscriptionId": "${AZURE_SUBSCRIPTION_ID}",
      "resourceGroup": "${AZURE_DNS_RESOURCE_GROUP}",
      "useWorkloadIdentityExtension": true
    }