apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: default
  labels:
    app: external-dns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: external-dns

  template:
    metadata:
      labels:
        app: external-dns
        azure.workload.identity/use: "true"

    spec:
      serviceAccountName: external-dns

      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.21.0

          args:
            - --source=gateway-httproute
            - --provider=azure
            - --azure-resource-group=${AZURE_DNS_RESOURCE_GROUP}
            - --azure-subscription-id=${AZURE_SUBSCRIPTION_ID}
            - --domain-filter=${DNS_ZONE_NAME}
            - --registry=txt
            - --txt-owner-id=project3
            - --log-level=info

          env:
            - name: AZURE_DNS_RESOURCE_GROUP
              value: "${AZURE_DNS_RESOURCE_GROUP}"

            - name: AZURE_SUBSCRIPTION_ID
              value: "${AZURE_SUBSCRIPTION_ID}"

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
              ephemeral-storage: 50Mi
            limits:
              memory: 128Mi
              ephemeral-storage: 100Mi

          volumeMounts:
            - name: azure-config
              mountPath: /etc/kubernetes
              readOnly: true

      volumes:
        - name: azure-config
          secret:
            secretName: external-dns-azure