apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: tasks-api-secrets
  namespace: default

spec:
  provider: azure

  parameters:
    clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    tenantId: "${AZURE_TENANT_ID}"

    objects: |
      array:
        - |
          objectName: mysql-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: mysql-fqdn
          objectType: secret
          objectVersion: ""
        - |
          objectName: mysql-database-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: mysql-admin-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-hostname
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-port
          objectType: secret
          objectVersion: ""

  secretObjects:
    - secretName: mysql-secret
      type: Opaque
      data:
        - objectName: mysql-admin-password
          key: MYSQL_PASSWORD
    - secretName: redis-secret
      type: Opaque
      data:
        - objectName: redis-password
          key: REDIS_PASSWORD
    - secretName: tasks-api-config-secret
      type: Opaque
      data:
        - objectName: mysql-fqdn
          key: MYSQL_HOST
        - objectName: mysql-database-name
          key: MYSQL_DATABASE
        - objectName: mysql-admin-username
          key: MYSQL_USER
        - objectName: redis-hostname
          key: REDIS_HOST
        - objectName: redis-port
          key: REDIS_PORT